### ISSUE TITLE
Error running Client

### ISSUE THREAD

**Issue by xlsong19** [Intel-bigdata/TensorFlowOnYARN#47]
hi,when I run the command
bin/ydl-tf launch --num_worker 2 --num_ps 2

The error infomation is :

17/10/27 14:34:43 INFO impl.TimelineClientImpl: Timeline service address: http://redoop:8188/ws/v1/timeline/
17/10/27 14:34:43 INFO client.RMProxy: Connecting to ResourceManager at redoop/172.16.137.181:8050
17/10/27 14:34:44 INFO client.Client: Starting YarnClient...
17/10/27 14:34:44 INFO util.ProcessRunner: Initializing Client
17/10/27 14:34:44 INFO util.Utils: Copying /home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-yarn-dist/target/tensorflow-yarn-0.1.0-SNAPSHOT/tensorflow-yarn-0.1.0-SNAPSHOT/lib/tensorflow-yarn-app-0.1.0-SNAPSHOT-jar-with-dependencies.jar to hdfs://redoop:8020/user/hdfs/TensorFlow/application_1509085631255_0002/tf.jar
17/10/27 14:34:45 INFO util.Utils: Copying /home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-yarn-dist/target/tensorflow-yarn-0.1.0-SNAPSHOT/tensorflow-yarn-0.1.0-SNAPSHOT/lib/libbridge.so to hdfs://redoop:8020/user/hdfs/TensorFlow/application_1509085631255_0002/libbridge.so
17/10/27 14:34:46 FATAL util.ProcessRunner: Error running Client
java.lang.NoSuchMethodError: org.apache.hadoop.yarn.api.records.URL.fromURI(Ljava/net/URI;)Lorg/apache/hadoop/yarn/api/records/URL;
	at org.hdl.tensorflow.yarn.util.Utils.addToLocalResources(Utils.java:77)
	at org.hdl.tensorflow.yarn.util.Utils.makeLocalResources(Utils.java:67)
	at org.hdl.tensorflow.yarn.client.LaunchCluster.run(LaunchCluster.java:124)
	at org.hdl.tensorflow.yarn.client.Client.run(Client.java:91)
	at org.hdl.tensorflow.yarn.util.ProcessRunner.run(ProcessRunner.java:44)
	at org.hdl.tensorflow.yarn.client.Client.main(Client.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

can you help me about the error? Hope your reply as soon as possible .Thanks~

**Comment by huafengw** [comment]
What's your hadoop version?

**Comment by xlsong19** [comment]
hadoop-2.7.1

**Comment by manuzhang** [comment]
The master version is based on hadoop-3. You may try out https://github.com/Intel-bigdata/TensorFlowOnYARN/tree/hadoop-2.7.3 which is based on hadoop-2.7
