### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by lvjia** [Intel-bigdata/TensorFlowOnYARN#49]
When I run the example program, the following exception occurs, how to solve it?
python examples/between-graph/mnist_feed.py --ps_hosts="gpu2.cmh:20382,gpu1.cmh:20384" --worker_hosts="gpu2.cmh:20378,gpu1.cmh:20380"  --task_index=0
Extracting /opt/mnist_test/MNIST_data/train-images-idx3-ubyte.gz
Extracting /opt/mnist_test/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /opt/mnist_test/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /opt/mnist_test/MNIST_data/t10k-labels-idx1-ubyte.gz
E0109 10:03:18.502502146    1045 ev_epoll1_linux.c:1051]     grpc epoll fd: 3
Traceback (most recent call last):
  File "examples/between-graph/mnist_feed.py", line 297, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "examples/between-graph/mnist_feed.py", line 224, in main
    run_training()
  File "examples/between-graph/mnist_feed.py", line 164, in run_training
    with sv.prepare_or_wait_for_session(master) as sess:
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 279, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'InTopKV2

**Comment by manuzhang** [comment]
This looks like a client side issue. Are you running the example against a newer version of tensorflow  or tensorflow-gpu ? This may only work with TF 1.0.0
